version: '3.8'

services:
  diabit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabit-app
    ports:
      - "3032:3032"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: always
